### ISSUE TITLE
All contacts are lost on Advanced parameter change

### ISSUE THREAD

**Issue by MageSlayer** [uTox/uTox#732] opened 2017-02-12 18:19 UTC
Tested using uTox 0.12.2 under Windows x64.
Any changes to network settings (UDP, IPv6, etc) result in full contact list cleaning. 
Really embarrassing!

**Comment by cebe** [comment] 2017-02-12 18:39
are you sure your tox is connected to the network after change?

**Comment by MageSlayer** [comment] 2017-02-12 18:52
Yes. Green status is showing.

**Comment by robinlinden** [comment] 2017-02-12 18:56
I can't recreate, running uTox 0.12.2 under Windows 10 x86-64.

My contact list disappears temporarily while uTox reconnects unless I ensure that it can't by forcing a proxy and give it incorrect/no info. Preventing uTox from reconnecting makes my contact list disappear until I change the network settings back to valid ones.

**Comment by endoffile78** [comment] 2017-02-12 19:05
Are your contacts still gone after restarting uTox.

**Comment by MageSlayer** [comment] 2017-02-12 19:15
Yes, completely clean contact list. See #733 :)

**Comment by MageSlayer** [comment] 2017-02-12 19:18
@robinlinden
Is it possible to force verbose logging under Windows somehow?
I am wondering if some other error seen as this issue. 
Maybe a side-effect of #730 leading to problems in memory allocator?

**Comment by cebe** [comment] 2017-02-12 19:20
to enable verbose logging you can run utox as `utox -vvvvv` from command line.

**Comment by GrayHatter** [comment] 2017-02-12 19:25
Is uTox set to show online friends only?

**Comment by MageSlayer** [comment] 2017-02-12 19:28
@GrayHatter 
Nope. It's the first thing I've tried.
"All contacts" is in effect.

@cebe 
Well, I ran utox with -vvvvv, but I detached from console (I use Far Manager) and no new logs were created near .exe file. Where can I find log file?

**Comment by GrayHatter** [comment] 2017-02-12 19:29
In re-reading the whole thread, this might be intended behavior. @MageSlayer can you explicitly describe the steps to reproduce this bug?

uTox dumps the contact list, and "reloads" it when toxcore reconnects. When you change a proxy setting, toxcore needs to restart. If you give it bad proxy information, it can't start. So uTox never reloads the friend list because Toxcore never start back up and provides that information.

**Comment by MageSlayer** [comment] 2017-02-12 19:35
@GrayHatter 
Np. I've just managed to reproduce it really easy.
1. Start uTox. New/defaults settings are in effect.
2. Wait for network connect (green status)
3. Add new user, wait for auth => ok
4. Test by text message -> ok
5. Go to Advanced tab, disable IPv6 => contact list disappears.
6. Wait for green status again => "All contacts" enabled, nothing in contact list (clicking All contacts vs Online contacts does nothing).

**Comment by GrayHatter** [comment] 2017-02-12 19:37
@MageSlayer thanks for the detailed report, can you do steps 1-4, and then instead of changing, network settings, can you try closing (making sure it's for sure closed, and not running in the background), and restarting uTox?

**Comment by MageSlayer** [comment] 2017-02-12 19:40
@GrayHatter 
Well, I can do that, but I have also #733, so no settings are saved and I get new account each time I run utox.

**Comment by GrayHatter** [comment] 2017-02-12 19:44
yeah, I'm 90% sure that's the real issue here. I'm going to close this, and then once that one gets solved. If this one still exists we'll reopen this one.

**Closed by GrayHatter** 2017-02-12 19:44 UTC
Labels: cat:bug

**Comment by n4skx** [comment] 2024-10-28 19:34
Sorry for bumping old issue. 

This bug affected me on Windows 11. I made a small change to network settings and suddenly all contacts were gone.

Really pissed me off.
