### ISSUE TITLE
loss of audio capture

### ISSUE THREAD

**Issue by 78uh78uj** [uTox/uTox#1507] opened 2021-01-02 14:55 UTC
### Overview

1. uTox version:
2. Operating system:
3. Desktop Environment/Window Manager (Linux/BSD only):

### Issue

Write your issue here.

**Comment by nurupo** [comment] 2021-01-04 18:31
Duplicate of https://github.com/uTox/uTox/issues/282.

**Comment by robinlinden** [comment] 2021-01-04 20:21
Thank you, nurupo!

**Closed by robinlinden** 2021-01-04 20:21 UTC
