### ISSUE TITLE
Messages received from the wrong user.

### ISSUE THREAD

**Issue by roranicus** [uTox/uTox#449] opened 2016-10-20 20:01 UTC
This issue happened on uTox 0.8.1, on Windows 7. It occured twice so far. 

My friend, who encountered the issue, received messages sent by someone else as coming from me, usually late. These messages were always initially received fine, but are seemingly "sent" again later, usually when logging on. Here's the scenario:

-uTox is opened.
-my friend clicks my username.
-he receives 2 or 3 lines of messages sent the previous session, sometimes by me, but often by another user. 

Hopefully this is isolated, but it sounds like a pretty serious issue. If that means anything, both I and the other user he has as a contact use Toxic.

**Comment by redmanmale** [comment] 2017-04-24 08:43
I've never seen anything like this, maybe it related with Toxic, it's hard to say.
Anyway it's been a while since 0.8.1, is this still reproducible on the latest version (0.15.0) or stale?

**Comment by GrayHatter** [comment] 2017-04-24 18:01
This is an issue I know I've fixed, so I'm going to close it. If it happens again open a new issue.

**Closed by GrayHatter** 2017-04-24 18:01 UTC
