### ISSUE TITLE
Dual Monitor Screen Capture not Working Win10

### ISSUE THREAD

**Issue by DeerSpotter** [uTox/uTox#171] opened 2016-01-15 00:09 UTC
##

**Comment by cebe** [comment] 2016-01-15 15:56
works on linux, so it seems to be windows issue.

**Comment by cebe** [comment] 2016-01-15 15:57
duplicate of #172?

**Comment by DeerSpotter** [comment] 2016-01-15 20:20
Sorry its a duplicate, this doesnt work with windows. Primarily this issue is seen when there are 3 monitors. I have not seen the issue with 2 monitors. On the 3 monitors the screen drag isnt visible or in other cases it drags on another monitor.

**Comment by GrayHatter** [comment] 2016-01-15 20:23
@DeerSpotter do you know how to get debug output from µTox?

what resolution are you running?

custom video card drivers?

can you describe the "drags on another monitor" in more detail?

**Comment by DeerSpotter** [comment] 2016-01-15 20:52
Sure im sorry for being vague. 

Can you let me know how to do a debug? 

Ill reply again for a full description of the problem

**Comment by DeerSpotter** [comment] 2016-01-15 20:55
Pressing the screenShot button activates the feature, the grey overlay appears on all the screens. 

When mousing over to any screen on a 3 monitor set up, and clicking to drag the square it wouldnt show the square dragging on the screen it was cropping a screen shot. it would show it on another screen instead. On one pc it took the screenshot where the square was being dragged, and on another pc it took the screen shot where we dragged the mouse but it showed the square being dragged on another screen instead. We have 2 pc setups that have 3 monitors.

**Comment by DeerSpotter** [comment] 2016-01-16 02:19
All drivers were updated. Using GeForce drivers. 

Resolution size of a 24in monitor. Recommended setting through windows 10

**Closed** 2021-06-23 20:28 UTC
Labels: cat:bug, pla:windows
