### ISSUE TITLE
At low DPI "Audio/Video" tab is unclickable

### ISSUE THREAD

**Issue by hjaf23** [uTox/uTox#377] opened 2016-06-27 13:51 UTC
Using Xubuntu 16.04 here. At latest uTox 64-bit client downloaded from http://tox.chat

When you go below %90 DPI "Audio/Video" settings tab becomes unclickable. The mouse icon doesn't change to hover state either.

**Comment by GrayHatter** [comment] 2016-06-27 18:37
Hey, I can't seem to duplicate this one. I need some more info on this one. Does the tab not show up? or is it just unclickable?

Have you tried resizing the window?

Does it work at 90%, and above, and only below it's broken?

Are any of the other buttons misaligned?

**Comment by tsudoko** [comment] 2016-06-27 19:32
For me it's unclickable for 80% and below, resizing the window doesn't seem to change anything.

**Comment by liwXO** [comment] 2016-08-17 18:53
For me it's also unclickable at 80% and below.

**Comment by GrayHatter** [comment] 2016-08-17 22:48
@tsudoko said he can't reproduce this anymore

Can you give me versions numbers @liwXO @HJafarli

**Comment by liwXO** [comment] 2016-08-18 19:53
@GrayHatter My uTox version is 0.9.7 (Stable).

**Comment by redmanmale** [comment] 2016-08-18 21:40
Confirmed on Windows 7 and 8.1 at 80% and below. At 90% and above it works fine (uTox v.0.9.7).

**Comment by redmanmale** [comment] 2017-01-04 22:28
Fixed in v.0.11.1 on Win 8.1

**Comment by redmanmale** [comment] 2017-01-24 15:14
Fixed in 0.12.1 on Win 7.

**Comment by robinlinden** [comment] 2017-01-24 15:17
Works fine on 0.12.1 for all DPI settings 50% <= x <= 200% on Windows 10.

**Closed** 2017-01-24 21:39 UTC
Labels: cat:bug, cat:user_interface
