### ISSUE TITLE
Tray icon shows up only when running the 2nd instance of uTox in OpenBox/Tint2

### ISSUE THREAD

**Issue by andoruB** [uTox/uTox#1029] opened 2017-09-01 15:12 UTC
uTox version: 0.16.1 (self-compiled from this: https://github.com/uTox/uTox/releases/tag/v0.16.1)
OS: Debian Sid 64-bit
DE: OpenBox 3.6.1 / Tint2 0.12.12

As the title suggests, the tray icon does not show up (as in, there's only empty space, and when I click it, uTox is restored) when I run it in a new instance. But if I start a 2nd instance of uTox, the icon shows up.

EDIT: right-clicking the tray icon also doesn't work, not sure if it's not implemented, or it's broken with this DM.

**Comment by GrayHatter** [comment] 2017-09-08 21:43
can you provide a few images, just so I can get a better idea of what the issue is.

Also can I have a copy of the debug output `utox -vvvvv`

**Comment by andoruB** [comment] 2017-09-08 22:25
Sure, here's the screenshot: 
https://i.imgur.com/9GphQ5F.png

And here's the output: 
https://hastebin.com/apolividev

You guys sure do know how to spice your error messages :D

**Comment by termac** [comment] 2017-09-11 09:07
For XLib the icon size does not seem to be read correctly. It is read as a pointer instead of as the actual value.
See #1050

**Comment by endoffile78** [comment] 2017-09-13 14:38
Fixed in #1050. Thank you @termac.

**Closed by endoffile78** 2017-09-13 14:38 UTC
Labels: cat:bug, cat:tray, pla:xlib

**Comment by andoruB** [comment] 2017-09-13 15:48
Thanks @termac!
