### ISSUE TITLE
Webcam preview crashes uTox

### ISSUE THREAD

**Issue by CsatiZoltan** [uTox/uTox#1169] opened 2018-01-19 21:49 UTC
### Overview

1. uTox version: 0.16.1
2. Operating system: Windows 7 64 bit

### Issue

When I click on the webcam icon on the *Audio & Video* tab, uTox crashes. Running the command `utox.exe -vvvv > utox_log.txt` produces the following:

```
WinFilesys:   Could not open file: C:\Users\Zoltan\AppData\Roaming\Tox\utox_save
Settings:     Unable to open utox_save.
Settings:     unable to load utox_save data
WinMain:      Normal windows build
WinMain:      Not skipping updater
Win Updater:  Starting
Win Updater:  Root d:\utox.exe
Win Updater:  Not the updater -- d:\utox.exe 
Win Pending:  Starting
Win Pending:  No updater waiting for us
Win Pending:  Bad file name -- d:\next_uTox.exe 
Windows:      WM_CREATE
Toxcore:      Using unencrypted save file
Toxcore:      Creating New Toxcore instance.
		IPv6 : 1
		UDP  : 1
		Proxy: 0  0
Friend:       Initializing friend list.
Friend:       Friendlist sucessfully initialized with 0 friends.
WinFilesys:   Could not open file: C:\Users\Zoltan\AppData\Roaming\Tox\avatars\880A9AA777BB4A2D946C2AB549143BD8F3E29463840EC118C64CAE6AF518123C.png
Avatar:       Unable to get saved avatar from disk for friend 880A9AA777BB4A2D946C2AB549143BD8F3E29463840EC118C64CAE6AF518123C
Windows Audio: default audio format: 1 65534 2 48000 384000 32 8

uToxVideo:    video init done!
Video:        Closing webcam
uTox:         Connected to DHT!
uToxVideo:    video init done!
uToxVideo:    started video
```

**Comment by pizdjuk** [comment] 2018-01-19 22:31
the same behavior here

**Comment by endoffile78** [comment] 2018-01-20 02:35
This issue might be fixed by this: #1170.

**Comment by pizdjuk** [comment] 2018-01-20 08:22
The issue is on Linux too

**Comment by endoffile78** [comment] 2018-01-20 09:16
@pizdjuk There was a fix for linux too, it was already merged: #1130.

**Comment by pizdjuk** [comment] 2018-01-20 10:34
Ah, sorry. The 0.16.1-4 works good. But I could compile and run it only yesterday (not easy to compile on Ubuntu 16.04, since there are no gcc7)

**Comment by endoffile78** [comment] 2018-01-21 14:34
@pizdjuk You shouln't need gcc7 you should be able to compile it with older versions of gcc or you can compile it with clang.

**Comment by avoidr** [comment] 2018-09-04 11:56
So this issue is fixed and can be closed?

**Comment by CsatiZoltan** [comment] 2018-09-04 12:07
Yes, now it works.

**Closed** 2018-09-04 13:34 UTC
Labels: cat:SEGV, cat:audio_video, cat:bug, pri:high
